import type { ModelEntry } from "../types";

/* Base-variant preset speaker library (`model: "seed-audio-1.0"`); the
   multilingual variant clones voices from `audio_urls` instead and has no
   preset list. "auto" leaves `voice` unset, which is what selects the
   multilingual variant by default (see `mode` below). */
const SEED_AUDIO_VOICE = [
  "auto",
  "ar_female_dina_uranus_bigtts",
  "ar_female_fatma_uranus_bigtts",
  "ar_male_youssef_uranus_bigtts",
  "de_female_bv081_uranus_bigtts",
  "de_male_seven_uranus_bigtts",
  "de_male_sven_uranus_bigtts",
  "en_female_allison_uranus_bigtts",
  "en_female_authoritative-british_uranus_bigtts",
  "en_female_authoritative-informative_uranus_bigtts",
  "en_female_brittney_uranus_bigtts",
  "en_female_dacey_uranus_bigtts",
  "en_female_hayley_uranus_bigtts",
  "en_female_jane_uranus_bigtts",
  "en_female_jenny_uranus_bigtts",
  "en_female_joanne_uranus_bigtts",
  "en_female_mel_uranus_bigtts",
  "en_female_myra_uranus_bigtts",
  "en_female_nadia_uranus_bigtts",
  "en_female_natasha_uranus_bigtts",
  "en_female_pleasant-female_uranus_bigtts",
  "en_female_sharron_uranus_bigtts",
  "en_female_skye_uranus_bigtts",
  "en_female_stokie_uranus_bigtts",
  "en_female_wenrouzhishijieshuonv_uranus_bigtts",
  "en_female_xinwenjieshuonv_uranus_bigtts",
  "en_male_adam-imitation_uranus_bigtts",
  "en_male_alberto_uranus_bigtts",
  "en_male_alex_uranus_bigtts",
  "en_male_bill-jones_uranus_bigtts",
  "en_male_bruce_uranus_bigtts",
  "en_male_cowboy-bob_uranus_bigtts",
  "en_male_david_uranus_bigtts",
  "en_male_deep-voice_uranus_bigtts",
  "en_male_diyuwenrounan_uranus_bigtts",
  "en_male_evil-guy-oxley_uranus_bigtts",
  "en_male_excited-male-voice_uranus_bigtts",
  "en_male_father-christmas_uranus_bigtts",
  "en_male_fernando-martinez_uranus_bigtts",
  "en_male_godfather_uranus_bigtts",
  "en_male_gollum_uranus_bigtts",
  "en_male_hades_uranus_bigtts",
  "en_male_jamie_uranus_bigtts",
  "en_male_jidongchuanjiaoshi_uranus_bigtts",
  "en_male_jimmy_uranus_bigtts",
  "en_male_joker_uranus_bigtts",
  "en_male_josh_uranus_bigtts",
  "en_male_kevin_uranus_bigtts",
  "en_male_knightley_uranus_bigtts",
  "en_male_marcus_uranus_bigtts",
  "en_male_michael-mouse_uranus_bigtts",
  "en_male_michael_uranus_bigtts",
  "en_male_motivational-coach_uranus_bigtts",
  "en_male_ronald_uranus_bigtts",
  "en_male_russell_uranus_bigtts",
  "en_male_tim_uranus_bigtts",
  "en_male_valentino_uranus_bigtts",
  "en_male_yangguangjieshuonan_uranus_bigtts",
  "es_female_bv084_uranus_bigtts",
  "es_male_dani_uranus_bigtts",
  "es_male_felipe_uranus_bigtts",
  "es_male_guillem_uranus_bigtts",
  "fr_male_usseau_uranus_bigtts",
  "id_female_bv161_uranus_bigtts",
  "id_female_bv161dialogue_uranus_bigtts",
  "id_female_bv161narration_uranus_bigtts",
  "id_female_bv164_uranus_bigtts",
  "id_female_f20_uranus_bigtts",
  "id_female_phulia_uranus_bigtts",
  "id_male_bv160_uranus_bigtts",
  "id_male_bv160dialogue_uranus_bigtts",
  "id_male_bv160narration_uranus_bigtts",
  "id_male_bv164dialogue_uranus_bigtts",
  "id_male_bv164narration_uranus_bigtts",
  "id_male_han_uranus_bigtts",
  "id_male_m08_uranus_bigtts",
  "it_male_enzo_uranus_bigtts",
  "ja_female_bv024_uranus_bigtts",
  "ja_female_bv520_uranus_bigtts",
  "ja_female_bv521_uranus_bigtts",
  "ja_female_bv522_uranus_bigtts",
  "ja_female_bv523_uranus_bigtts",
  "ja_female_minimi_uranus_bigtts",
  "ja_female_shirou_uranus_bigtts",
  "ja_male_bv524_uranus_bigtts",
  "jp_female_minimi_uranus_bigtts",
  "ko_female_bv546_uranus_bigtts",
  "ko_male_bv545_uranus_bigtts",
  "ko_male_m03_uranus_bigtts",
  "ko_male_shane_uranus_bigtts",
  "kr_male_shane_uranus_bigtts",
  "ms_male_ham_uranus_bigtts",
  "ms_male_naim_uranus_bigtts",
  "mx_female_bv065_uranus_bigtts",
  "mx_female_bv166dialogue_uranus_bigtts",
  "mx_female_bv166emotion_uranus_bigtts",
  "mx_female_bv166narrator_uranus_bigtts",
  "mx_female_leslie_uranus_bigtts",
  "mx_male_bv165dialogue_uranus_bigtts",
  "mx_male_bv165narrator_uranus_bigtts",
  "mx_male_felipe_uranus_bigtts",
  "mx_male_marcelo_uranus_bigtts",
  "pt_female_bv173_uranus_bigtts",
  "pt_female_bv173dialogue_uranus_bigtts",
  "pt_female_bv173emotion_uranus_bigtts",
  "pt_female_bv173narrator_uranus_bigtts",
  "pt_female_bv530_uranus_bigtts",
  "pt_female_mari_uranus_bigtts",
  "pt_male_bv172_uranus_bigtts",
  "pt_male_bv172dialogue_uranus_bigtts",
  "pt_male_bv172emotion_uranus_bigtts",
  "pt_male_bv172narrator_uranus_bigtts",
  "pt_male_bv531_uranus_bigtts",
  "pt_male_martins_uranus_bigtts",
  "pt_male_rael_uranus_bigtts",
  "ru_female_af07_uranus_bigtts",
  "ru_female_irinae_uranus_bigtts",
  "ru_female_sophie_uranus_bigtts",
  "ru_male_pavel_uranus_bigtts",
  "ru_male_vlad_uranus_bigtts",
  "tl_female_annika_uranus_bigtts",
  "tl_female_hervie_uranus_bigtts",
  "tl_male_ed_uranus_bigtts",
  "vi_female_hong_uranus_bigtts",
  "vi_female_ling_uranus_bigtts",
  "vi_female_linh_uranus_bigtts",
  "vi_female_partner_uranus_bigtts",
  "vi_female_ruan_uranus_bigtts",
  "vi_female_wu_uranus_bigtts",
  "vi_male_wumg_uranus_bigtts",
  "zh_female_cancan_uranus_bigtts",
  "zh_female_jitangnv_uranus_bigtts",
  "zh_female_kefunvsheng_uranus_bigtts",
  "zh_female_kiwi_uranus_bigtts",
  "zh_female_linjianvhai_uranus_bigtts",
  "zh_female_liuchangnv_uranus_bigtts",
  "zh_female_meilinvyou_uranus_bigtts",
  "zh_female_mizai_uranus_bigtts",
  "zh_female_peiqi_uranus_bigtts",
  "zh_female_qingxinnvsheng_uranus_bigtts",
  "zh_female_sajiaoxuemei_uranus_bigtts",
  "zh_female_shuangkuaisisi_uranus_bigtts",
  "zh_female_tianmeitaozi_uranus_bigtts",
  "zh_female_tianmeixiaoyuan_uranus_bigtts",
  "zh_female_vv_uranus_bigtts",
  "zh_female_xiaohe_uranus_bigtts",
  "zh_female_xiaoxue_uranus_bigtts",
  "zh_female_yingyujiaoxue_uranus_bigtts",
  "zh_female_yuanqi_uranus_bigtts",
  "zh_male_dayi_uranus_bigtts",
  "zh_male_liufei_uranus_bigtts",
  "zh_male_m191_uranus_bigtts",
  "zh_male_ruyayichen_uranus_bigtts",
  "zh_male_shaonianzixin_uranus_bigtts",
  "zh_male_sophie_uranus_bigtts",
  "zh_male_sunwukong_uranus_bigtts",
  "zh_male_taocheng_uranus_bigtts",
] as const;

/* `model` picks the variant: "seed-audio-1.0-multilingual" (20 languages,
   voice cloning only) or "seed-audio-1.0" (English/Chinese, preset voices).
   "auto" leaves it unset so the platform infers from whether `voice` is set. */
const SEED_AUDIO_MODE = ["auto", "seed-audio-1.0-multilingual", "seed-audio-1.0"] as const;

/* All-in-one dialogue/music/ambience/SFX generator. Voice cloning references
   (up to 3 clips) are the `audio` role; the single scene-matching image
   reference is `reference`. `sample_rate`, `bitrate`, and `channel` are
   left off the rail as output plumbing, not creative choices; so is
   `enable_subtitles`, which only adds a timing sidecar to the same audio. */
export const seedAudio1: ModelEntry = {
  id: "seed-audio-1.0",
  surface: "audio",
  label: "Seed Audio 1.0",
  vendor: "bytedance",
  roles: { audio: 3, reference: 1 },
  settings: {
    mode: { type: "enum", values: SEED_AUDIO_MODE, default: "auto" },
    voice: { type: "enum", values: SEED_AUDIO_VOICE, default: "auto" },
    outputFormat: { type: "enum", values: ["mp3", "wav", "pcm", "ogg_opus"], default: "mp3" },
    speed: { type: "range", min: 0.5, max: 2, default: 1, step: 0.1 },
    volume: { type: "range", min: 0.5, max: 2, default: 1, step: 0.1 },
    pitch: { type: "range", min: -12, max: 12, default: 0, step: 1 },
  },
  operations: [
    {
      apiId: "bytedance/seed-audio-1.0/text-to-audio",
      media: {
        audio: { field: "audio_urls", many: true },
        reference: { field: "image_url" },
      },
      params: {
        mode: { field: "model", omit: ["auto"] },
        voice: { field: "voice", omit: ["auto"] },
        outputFormat: "output_format",
        speed: "speed",
        volume: "volume",
        pitch: "pitch",
      },
    },
  ],
};

export const bytedanceAudio: readonly ModelEntry[] = [seedAudio1];
